// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomNavbar from "@/Shared/CustomNavbar";
import { Roboto } from 'next/font/google';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Add more weights if needed
  variable: '--font-roboto',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className="antialiased font-roboto">
        <CustomNavbar />
        <main>{children}</main>
      </body>
    </html>
  );
}

